/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as OracleSubscriptionAllowedConsumerContractJson } from "../oracles/OracleSubscriptionAllowedConsumer.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace OracleSubscriptionAllowedConsumerTypes {
  export type Fields = {
    consumerAddress: Address;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getConsumerAddress: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  OracleSubscriptionAllowedConsumerInstance,
  OracleSubscriptionAllowedConsumerTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as OracleSubscriptionAllowedConsumerTypes.Fields;
  }

  at(address: string): OracleSubscriptionAllowedConsumerInstance {
    return new OracleSubscriptionAllowedConsumerInstance(address);
  }

  tests = {
    getConsumerAddress: async (
      params: Omit<
        TestContractParams<
          OracleSubscriptionAllowedConsumerTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<Address>> => {
      return testMethod(this, "getConsumerAddress", params);
    },
  };
}

// Use this object to test and deploy the contract
export const OracleSubscriptionAllowedConsumer = new Factory(
  Contract.fromJson(
    OracleSubscriptionAllowedConsumerContractJson,
    "",
    "e4ac1069a1aea968d177741c290e109285ba3771c8df9c94e07d80d328a4c0c3"
  )
);

// Use this class to interact with the blockchain
export class OracleSubscriptionAllowedConsumerInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<OracleSubscriptionAllowedConsumerTypes.State> {
    return fetchContractState(OracleSubscriptionAllowedConsumer, this);
  }

  methods = {
    getConsumerAddress: async (
      params?: OracleSubscriptionAllowedConsumerTypes.CallMethodParams<"getConsumerAddress">
    ): Promise<
      OracleSubscriptionAllowedConsumerTypes.CallMethodResult<"getConsumerAddress">
    > => {
      return callMethod(
        OracleSubscriptionAllowedConsumer,
        this,
        "getConsumerAddress",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<
    Calls extends OracleSubscriptionAllowedConsumerTypes.MultiCallParams
  >(
    calls: Calls
  ): Promise<OracleSubscriptionAllowedConsumerTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      OracleSubscriptionAllowedConsumer,
      this,
      calls,
      getContractByCodeHash
    )) as OracleSubscriptionAllowedConsumerTypes.MultiCallResults<Calls>;
  }
}
